Returning config file from server

diff --git a/config/recipes/templates/unicorn_init.erb b/config/recipes/templates/unicorn_init.erb
--- a/config/recipes/templates/unicorn_init.erb
+++ b/config/recipes/templates/unicorn_init.erb
@@ -21,65 +21,65 @@ set -u
 OLD_PIN="$PID.oldbin"
 
 sig () {
-  test -s "$PID" && kill -$1 `cat $PID`
+test -s "$PID" && kill -$1 `cat $PID`
 }
 
 oldsig () {
-  test -s $OLD_PIN && kill -$1 `cat $OLD_PIN`
+test -s $OLD_PIN && kill -$1 `cat $OLD_PIN`
 }
 
 run () {
-  if [ "$(id -un)" = "$AS_USER" ]; then
-    eval $1
-  else
-    su -c "$1" - $AS_USER
-  fi
+if [ "$(id -un)" = "$AS_USER" ]; then
+eval $1
+else
+su -c "$1" - $AS_USER
+fi
 }
 
 case "$1" in
 start)
-  sig 0 && echo >&2 "Already running" && exit 0
-  echo >&2 "$CMD"
-  run "$CMD"
-  ;;
+sig 0 && echo >&2 "Already running" && exit 0
+echo >&2 "$CMD"
+run "$CMD"
+;;
 stop)
-  sig QUIT && exit 0
-  echo >&2 "Not running"
-  ;;
+sig QUIT && exit 0
+echo >&2 "Not running"
+;;
 force-stop)
-  sig TERM && exit 0
-  echo >&2 "Not running"
-  ;;
+sig TERM && exit 0
+echo >&2 "Not running"
+;;
 restart|reload)
-  sig HUP && echo reloaded OK && exit 0
-  echo >&2 "Couldn't reload, starting '$CMD' instead"
-  run "$CMD"
-  ;;
+sig HUP && echo reloaded OK && exit 0
+echo >&2 "Couldn't reload, starting '$CMD' instead"
+run "$CMD"
+;;
 upgrade)
-  if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
-  then
-    n=$TIMEOUT
-    while test -s $OLD_PIN && test $n -ge 0
-    do
-      printf '.' && sleep 1 && n=$(( $n - 1 ))
-    done
-    echo
+if sig USR2 && sleep 2 && sig 0 && oldsig QUIT
+then
+n=$TIMEOUT
+while test -s $OLD_PIN && test $n -ge 0
+do
+printf '.' && sleep 1 && n=$(( $n - 1 ))
+done
+echo
 
-    if test $n -lt 0 && test -s $OLD_PIN
-    then
-      echo >&2 "$OLD_PIN still exists after $TIMEOUT seconds"
-      exit 1
-    fi
-    exit 0
-  fi
-  echo >&2 "Couldn't upgrade, starting '$CMD' instead"
-  run "$CMD"
-  ;;
+if test $n -lt 0 && test -s $OLD_PIN
+then
+echo >&2 "$OLD_PIN still exists after $TIMEOUT seconds"
+exit 1
+fi
+exit 0
+fi
+echo >&2 "Couldn't upgrade, starting '$CMD' instead"
+run "$CMD"
+;;
 reopen-logs)
-  sig USR1
-  ;;
+sig USR1
+;;
 *)
-  echo >&2 "Usage: $0 < start|stop|restart|upgrade|force-stop|reopen-logs >"
-  exit 1
-  ;;
+echo >&2 "Usage: $0 < start|stop|restart|upgrade|force-stop|reopen-logs >"
+exit 1
+;;
 esac
